version = 0.1

[default.global.parameters]
stack_name = "Fancy1337API"

[default.deploy]
[default.deploy.parameters]
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
s3_prefix = "fancy-1337-api"
region = "eu-north-1"
s3_bucket = "elias-brange-ci-cd-eu-north-1"
